[package]
name = "semver_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
struct_marked_non_exhaustive = []
struct_missing = []
struct_pub_field_missing = []
enum_missing = []
enum_variant_missing = []
enum_variant_added = []
unit_struct_changed_kind = []
variant_marked_non_exhaustive = []
