name: Publish new version to crates.io

on:
  push:
    branches:
      - check-semver-pre-publish

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  publish-pipeline:
    name: Test and publish new version to crates.io
    runs-on: ubuntu-latest
    needs:
      - pre-publish-crate
    steps:
      - run: exit 0

  pre-publish-crate:
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v1
